// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
// source: filters.proto
//
// database: v1
// schema:   venue_v1
//
// orm — https://github.com/the-protobuf-project/orm

package venuev1

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// OperatorStore provides typed CRUD access to Operator records.
// Operator is the referenced parent so the venue's reference resolves to a real table (a hard FK) instead of degrading to a soft reference.
type OperatorStore struct{ DB *gorm.DB }

// Compile-time proof that OperatorStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Operator] = (*OperatorStore)(nil)

// NewOperatorStore returns a OperatorStore backed by db.
func NewOperatorStore(db *gorm.DB) *OperatorStore { return &OperatorStore{DB: db} }

// Create inserts m.
func (s *OperatorStore) Create(ctx context.Context, m *Operator) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Operator records matching opts.
func (s *OperatorStore) List(ctx context.Context, opts gormx.ListOptions) ([]Operator, error) {
	var out []Operator
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Operator records matching opts.Where
// (pagination and ordering are ignored).
func (s *OperatorStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&Operator{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *OperatorStore) Update(ctx context.Context, m *Operator) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Operator with the given primary key.
func (s *OperatorStore) GetByID(ctx context.Context, id string) (*Operator, error) {
	var m Operator
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Operator with the given primary key.
func (s *OperatorStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Operator{}, "id = ?", id).Error
}

// GetByName fetches the Operator with the given name (a unique column).
func (s *OperatorStore) GetByName(ctx context.Context, v string) (*Operator, error) {
	var m Operator
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}
