// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
// source: filters.proto
//
// database: v1
// schema:   venue_v1
//
// orm — https://github.com/the-protobuf-project/orm

package venuev1

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// VenueStore provides typed CRUD access to Venue records.
// Venue exercises the filters emitter: type-derived kinds for every scalar shape (text, enum, date, timestamp, int, bool, tags), the search opt-in, the filterable/sortable opt-outs, a resource reference (equality-only Ref kind), and shapes that are always excluded (JSONB attributes, the synthesized key).
type VenueStore struct{ DB *gorm.DB }

// Compile-time proof that VenueStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Venue] = (*VenueStore)(nil)

// NewVenueStore returns a VenueStore backed by db.
func NewVenueStore(db *gorm.DB) *VenueStore { return &VenueStore{DB: db} }

// Create inserts m.
func (s *VenueStore) Create(ctx context.Context, m *Venue) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Venue records matching opts.
func (s *VenueStore) List(ctx context.Context, opts gormx.ListOptions) ([]Venue, error) {
	var out []Venue
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Venue records matching opts.Where
// (pagination and ordering are ignored).
func (s *VenueStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&Venue{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *VenueStore) Update(ctx context.Context, m *Venue) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Venue with the given primary key.
func (s *VenueStore) GetByID(ctx context.Context, id string) (*Venue, error) {
	var m Venue
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Venue with the given primary key.
func (s *VenueStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Venue{}, "id = ?", id).Error
}

// GetByName fetches the Venue with the given name (a unique column).
func (s *VenueStore) GetByName(ctx context.Context, v string) (*Venue, error) {
	var m Venue
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// ListByOperatorID returns the Venue records whose operator matches id, with opts applied.
func (s *VenueStore) ListByOperatorID(ctx context.Context, id string, opts gormx.ListOptions) ([]Venue, error) {
	var out []Venue
	q := opts.Apply(s.DB.WithContext(ctx).Where("operator = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
