// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm (unknown)
// 	protoc             (unknown)
// source: reserved_words.proto
//
// database: reserved_db
// schema:   public
//
// protorm — https://github.com/oh-tarnished/protorm

package public

// State is the account lifecycle state.
type State string

// State values as stored in the database.
const (
	StateUnspecified State = "unspecified"
	StateActive      State = "active"
	StateClosed      State = "closed"
)

// Account is forced onto the reserved table name "user" via a table override, with reserved-word columns and a composite UNIQUE index over them.
type Account struct {
	// name: IDENTIFIER → PRIMARY KEY.
	Name string `gorm:"column:name;primaryKey;not null" json:"name"`
	// order is a reserved word; also carries a single-column index.
	Order *string `gorm:"column:order;index" json:"order,omitempty"`
	// select is a reserved word.
	Select *string `gorm:"column:select" json:"select,omitempty"`
	// state exercises a quoted, schema-qualified enum type reference.
	State State `gorm:"column:state;not null" json:"state" validate:"required"`
}

func (*Account) TableName() string { return "public.user" }
