// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
//
// database: v1
// package:  filterx
//
// Shared AIP-160 filter / AIP-132 order_by / paginated-list engines driven by the generated per-schema specs.
//
// orm — https://github.com/the-protobuf-project/orm

// Package filterx is the generated filter/order/list SDK: the Condition
// vocabulary an AIP-160 filter parses into, the Spec data model the per-schema
// filters.go files instantiate, the shared semantics (enum normalization,
// date/number validation, ILIKE escaping, sort allowlists, page math), and the
// two chainable engines built from a Spec — Gorm[M] for SQL and Hasura[M] for
// GraphQL. Engines are code, specs are data: one Spec per table drives both
// backends, so both accept identical filter strings by construction.
package filterx

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// ErrInvalid marks a caller mistake — an unknown filter/sort field, an
// unsupported operator, or a malformed value. Callers translate it to their
// invalid-argument error (e.g. a gRPC InvalidArgument) with errors.Is.
var ErrInvalid = errors.New("invalid filter or order_by")

// Op is the comparison in a single filter term.
type Op int

const (
	// OpEq is the `=` operator (exact match).
	OpEq Op = iota
	// OpNeq is the `!=` operator (negated exact match).
	OpNeq
	// OpHas is the `:` operator (substring / membership match).
	OpHas
	// OpLte is the `<=` operator (ordered kinds only).
	OpLte
	// OpGte is the `>=` operator (ordered kinds only).
	OpGte
)

// Condition is one parsed term of a filter expression. A condition with an
// empty Field is a bareword free-text term, matched against the spec's Search
// columns. Conditions in a slice are AND-combined.
type Condition struct {
	Field string
	Op    Op
	Value string
}

// Kind classifies a field's filter semantics; it decides which operators apply
// and how values are validated and normalized.
type Kind int

const (
	// KindText is a string column: = / != exact, `:` case-insensitive contains.
	KindText Kind = iota
	// KindEnum is a stored enum column: = / !=, accepting the bare value name
	// ("ROOM") or the fully-qualified proto form ("UNIT_TYPE_ROOM").
	KindEnum
	// KindDate is a calendar-date column: = / <= / >= against YYYY-MM-DD.
	KindDate
	// KindTimestamp is a timestamptz column: = / <= / >= against RFC 3339 (a
	// bare date is accepted as its midnight-UTC instant).
	KindTimestamp
	// KindInt is an integral column: = / != / <= / >=.
	KindInt
	// KindFloat is a floating-point column: = / != / <= / >=.
	KindFloat
	// KindBool is a boolean column: = / != against true|false.
	KindBool
	// KindRef is a stored resource-reference id: = / != identity match only.
	KindRef
	// KindTags is a text[] column: `:` containment of one tag.
	KindTags
)

// FieldSpec describes one filterable field: its physical column, its kind, and
// (for enums) the proto value prefix stripped during normalization.
type FieldSpec struct {
	Column     string
	Kind       Kind
	EnumPrefix string
}

// Spec is one table's filter/order surface. Instances are generated per schema
// (see each <schema>/filters.go); both engines consume the same Spec.
type Spec struct {
	// Table is the quoted, schema-qualified physical table the gorm engine
	// prefixes columns with (unused by the hasura engine).
	Table string
	// Fields maps API filter field names to their specs.
	Fields map[string]FieldSpec
	// Search lists the columns a bareword free-text term matches
	// (case-insensitive contains, OR-combined).
	Search []string
	// Sort maps order_by field names to their physical columns.
	Sort map[string]string
}

// --- value normalization and validation ---------------------------------------

// NormalizeEnum maps a filter value onto the stored enum form: uppercase with
// the proto value prefix stripped, so both "ROOM" and "UNIT_TYPE_ROOM" match.
func NormalizeEnum(f FieldSpec, v string) string {
	return strings.TrimPrefix(strings.ToUpper(v), f.EnumPrefix)
}

// ParseDate validates a YYYY-MM-DD filter value.
func ParseDate(v string) (time.Time, error) {
	t, err := time.Parse("2006-01-02", v)
	if err != nil {
		return time.Time{}, fmt.Errorf("%w: %q is not a date (want YYYY-MM-DD)", ErrInvalid, v)
	}
	return t, nil
}

// ParseTimestamp validates an RFC 3339 filter value, accepting a bare date as
// its midnight-UTC instant.
func ParseTimestamp(v string) (time.Time, error) {
	if t, err := time.Parse(time.RFC3339, v); err == nil {
		return t, nil
	}
	if t, err := time.Parse("2006-01-02", v); err == nil {
		return t, nil
	}
	return time.Time{}, fmt.Errorf("%w: %q is not a timestamp (want RFC 3339)", ErrInvalid, v)
}

// ParseInt validates an integral filter value.
func ParseInt(v string) (int64, error) {
	n, err := strconv.ParseInt(v, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("%w: %q is not an integer", ErrInvalid, v)
	}
	return n, nil
}

// ParseFloat validates a numeric filter value.
func ParseFloat(v string) (float64, error) {
	n, err := strconv.ParseFloat(v, 64)
	if err != nil {
		return 0, fmt.Errorf("%w: %q is not a number", ErrInvalid, v)
	}
	return n, nil
}

// ParseBool validates a boolean filter value.
func ParseBool(v string) (bool, error) {
	b, err := strconv.ParseBool(v)
	if err != nil {
		return false, fmt.Errorf("%w: %q is not a boolean", ErrInvalid, v)
	}
	return b, nil
}

// RefID reduces a resource-reference filter value to the bare id a reference
// column stores: the last path segment of an AIP resource name ("users/7" →
// "7"), or the value unchanged when it has no path.
func RefID(v string) string {
	if i := strings.LastIndex(v, "/"); i >= 0 {
		return v[i+1:]
	}
	return v
}

// ContainsPattern builds a case-insensitive "contains" LIKE pattern, escaping
// the LIKE wildcards in the user value so they match literally. Pair it with
// an `ESCAPE '\'` clause (the gorm engine does).
func ContainsPattern(v string) string {
	r := strings.NewReplacer(`\`, `\\`, `%`, `\%`, `_`, `\_`)
	return "%" + r.Replace(v) + "%"
}

// ILikePattern builds the unescaped "contains" pattern GraphQL _ilike uses.
func ILikePattern(v string) string { return "%" + v + "%" }

// CamelCase converts a snake_case column name to the camelCase field name a
// Hasura DDN schema exposes ("display_name" → "displayName").
func CamelCase(snake string) string {
	parts := strings.Split(snake, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

// --- order_by ------------------------------------------------------------------

// OrderTerm is one resolved order_by term: a physical column and direction.
type OrderTerm struct {
	Column string
	Desc   bool
}

// OrderTerms parses an AIP-132 order_by string ("expiry_date desc, name")
// against the spec's sort allowlist. Unknown fields and malformed terms are
// rejected with ErrInvalid; the empty string yields no terms.
func OrderTerms(spec Spec, orderBy string) ([]OrderTerm, error) {
	orderBy = strings.TrimSpace(orderBy)
	if orderBy == "" {
		return nil, nil
	}
	parts := strings.Split(orderBy, ",")
	terms := make([]OrderTerm, 0, len(parts))
	for _, part := range parts {
		fields := strings.Fields(part)
		if len(fields) == 0 || len(fields) > 2 {
			return nil, fmt.Errorf("%w: malformed order_by term %q", ErrInvalid, strings.TrimSpace(part))
		}
		col, ok := spec.Sort[fields[0]]
		if !ok {
			return nil, fmt.Errorf("%w: cannot sort by %q", ErrInvalid, fields[0])
		}
		term := OrderTerm{Column: col}
		if len(fields) == 2 {
			switch strings.ToLower(fields[1]) {
			case "asc":
			case "desc":
				term.Desc = true
			default:
				return nil, fmt.Errorf("%w: invalid sort direction %q", ErrInvalid, fields[1])
			}
		}
		terms = append(terms, term)
	}
	return terms, nil
}

// --- pagination ------------------------------------------------------------------

// ListInput is the request shape both list engines take: AIP page controls, an
// order_by string, and the parsed filter conditions.
type ListInput struct {
	PageSize  int32
	PageToken string
	OrderBy   string
	Filter    []Condition
}

const (
	defaultPageSize = 50
	maxPageSize     = 1000
)

// PageBounds clamps the page size to [1, maxPageSize] (defaulting when unset)
// and decodes the opaque page token into a row offset.
func PageBounds(in ListInput) (limit, offset int) {
	limit = int(in.PageSize)
	switch {
	case limit <= 0:
		limit = defaultPageSize
	case limit > maxPageSize:
		limit = maxPageSize
	}
	return limit, decodeOffset(in.PageToken)
}

// EncodeOffset mints the opaque next-page token for a row offset.
func EncodeOffset(offset int) string {
	return base64.RawURLEncoding.EncodeToString([]byte(strconv.Itoa(offset)))
}

func decodeOffset(token string) int {
	if token == "" {
		return 0
	}
	raw, err := base64.RawURLEncoding.DecodeString(token)
	if err != nil {
		return 0
	}
	n, err := strconv.Atoi(string(raw))
	if err != nil || n < 0 {
		return 0
	}
	return n
}

// NextToken trims a limit+1 result page and mints the next-page token when a
// further page exists. Engines fetch limit+1 rows and hand them here.
func NextToken[M any](rows []M, limit, offset int) ([]M, string) {
	if len(rows) > limit {
		return rows[:limit], EncodeOffset(offset + limit)
	}
	return rows, ""
}

// --- observability ----------------------------------------------------------------

// Observer receives the engines' trace spans and debug events; wire one with
// the engines' Observe option (engines observe nothing by default). Adapt your
// telemetry runtime to this interface — with the pulse opt, a ready-made
// pulse-go adapter (PulseObserver) is generated in this package.
type Observer interface {
	// Span wraps one engine operation (e.g. a list fetch) in a trace span.
	Span(ctx context.Context, name string, fn func(context.Context) error) error
	// Debug reports a non-fatal engine event (e.g. a rejected filter).
	Debug(msg string, kv map[string]any)
}

// NopObserver observes nothing.
type NopObserver struct{}

// Span runs fn without tracing.
func (NopObserver) Span(ctx context.Context, _ string, fn func(context.Context) error) error {
	return fn(ctx)
}

// Debug discards the event.
func (NopObserver) Debug(string, map[string]any) {}
