// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
// source: telemetry.proto
//
// database: weather_db
// schema:   weather
//
// orm — https://github.com/the-protobuf-project/orm

package weather

// Reading exercises the telemetry emitter's default path: instrumented store methods with a default span prefix, and labeled fields carrying span attribute struct tags (one default name, one explicit override).
type Reading struct {
	// Unique identifier for the record.
	ID   string `gorm:"column:id;primaryKey;not null" json:"id"`
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// Station labels every span for this table (default attribute name).
	Station string `gorm:"column:station;not null" json:"station" validate:"required" opentelementry:"trace:reading.station"`
	// Condition carries an explicit attribute name override.
	Condition    *string  `gorm:"column:condition" json:"condition,omitempty" opentelementry:"trace:weather.condition"`
	TemperatureC *float64 `gorm:"column:temperature_c" json:"temperature_c,omitempty"`
}

func (*Reading) TableName() string { return "weather.readings" }

// Sensor overrides the span prefix and disables its op metrics, keeping spans only.
type Sensor struct {
	// Unique identifier for the record.
	ID     string `gorm:"column:id;primaryKey;not null" json:"id"`
	Name   string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	Serial string `gorm:"column:serial;not null" json:"serial" validate:"required"`
}

func (*Sensor) TableName() string { return "weather.sensors" }

// Calibration opts out of instrumentation entirely, proving a table-level (orm.v1.telemetry).enabled=false override wins over the tree-wide default.
type Calibration struct {
	// Unique identifier for the record.
	ID    string  `gorm:"column:id;primaryKey;not null" json:"id"`
	Name  string  `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	Notes *string `gorm:"column:notes" json:"notes,omitempty"`
}

func (*Calibration) TableName() string { return "weather.calibrations" }
